#!/usr/bin/env python3
"""
GoogleClaw — Local Server
Serves the frontend, proxies gateway calls, and auto-connects from config.json.

Usage:
  python3 serve.py                  # default port 8080
  python3 serve.py --port 9090
  python3 serve.py --no-browser     # don't auto-open browser
"""

import json
import os
import sys
import threading
import webbrowser
import argparse
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.request import urlopen, Request
from urllib.error import URLError
import urllib.parse

# ── Config ────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH  = os.path.join(SCRIPT_DIR, "config.json")
FRONTEND_DIR = os.path.join(SCRIPT_DIR, "frontend")

# GoogleClaw Google OAuth app — set via environment variables in docker-compose.yml
GC_GOOGLE_CLIENT_ID     = os.environ.get("GC_GOOGLE_CLIENT_ID", "")
GC_GOOGLE_CLIENT_SECRET = os.environ.get("GC_GOOGLE_CLIENT_SECRET", "")

def load_config():
    if not os.path.exists(CONFIG_PATH):
        print(f"[serve] ⚠  config.json not found at {CONFIG_PATH}")
        print("[serve]    Run `python3 setup.py` first to create it.")
        return {}
    with open(CONFIG_PATH) as f:
        return json.load(f)

# ── Handler ───────────────────────────────────────────────────────────────────
class GCHandler(SimpleHTTPRequestHandler):
    """Serves frontend/ static files + /bootstrap.js + /proxy/tools/invoke"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=FRONTEND_DIR, **kwargs)

    # ── CORS headers ──────────────────────────────────────────────────────────
    def send_cors(self):
        self.send_header("Access-Control-Allow-Origin",  "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_cors()
        self.end_headers()

    # ── Dynamic routes ────────────────────────────────────────────────────────
    def do_GET(self):
        if self.path == "/bootstrap.js":
            self._serve_bootstrap()
        elif self.path.startswith("/proxy/data/"):
            self._serve_data_file()
        elif self.path.startswith("/proxy/agent-prompt/"):
            self._serve_agent_prompt()
        elif self.path in ("/", ""):
            # Redirect to setup if config.json missing
            if not os.path.exists(CONFIG_PATH):
                self.send_response(302)
                self.send_header("Location", "/setup")
                self.end_headers()
            else:
                self.path = "/web.html"
                super().do_GET()
        elif self.path == "/setup":
            self.path = "/setup.html"
            super().do_GET()
        elif self.path.startswith("/setup/google-auth/callback"):
            self._google_auth_callback()
        elif self.path == "/setup/google-auth/status":
            self._google_auth_status()
        else:
            super().do_GET()

    def do_POST(self):
        if self.path == "/proxy/tools/invoke":
            self._proxy_invoke()
        elif self.path == "/proxy/config":
            self._write_config()
        elif self.path == "/setup/save":
            self._setup_save()
        elif self.path == "/setup/test-shopify":
            self._setup_test_shopify()
        elif self.path == "/setup/google-auth/start":
            self._google_auth_start()
        else:
            self.send_response(404)
            self.end_headers()

    # ── /bootstrap.js — auto-connect config for the frontend ─────────────────
    def _serve_bootstrap(self):
        cfg = load_config()
        gw_url   = cfg.get("gateway", {}).get("url", "")
        gw_token = cfg.get("gateway", {}).get("token", "")
        inst     = cfg.get("instance", {})
        store    = cfg.get("store", {})
        thresh   = cfg.get("thresholds", {})

        js = f"""// Auto-generated by serve.py — do not edit manually
window.GC_BOOTSTRAP = {{
  gatewayUrl:   "/proxy/tools/invoke",
  gatewayToken: "{gw_token}",
  managed:      true,
  instance: {{
    name:     "{inst.get('name','')}",
    owner:    "{inst.get('owner','')}",
    botName:  "{inst.get('bot_name','')}",
    timezone: "{inst.get('timezone','Europe/Amsterdam')}"
  }},
  store: {{
    niche:    "{store.get('niche','')}",
    market:   "{store.get('market','')}",
    language: "{store.get('language','')}"
  }},
  thresholds: {{
    scale_roas:    {thresh.get('scale_roas', 3.0)},
    alert_roas:    {thresh.get('alert_roas', 1.0)},
    alert_days:    {thresh.get('alert_days', 3)},
    min_price:     {thresh.get('min_price', 40)},
    autopub_score: {thresh.get('autopub_score', 75)},
    daily_limit:   {thresh.get('daily_limit', 10)}
  }}
}};
"""
        body = js.encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/javascript")
        self.send_header("Content-Length", str(len(body)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(body)

    # ── /proxy/tools/invoke — proxy to OpenClaw gateway ──────────────────────
    def _proxy_invoke(self):
        cfg      = load_config()
        gw_url   = cfg.get("gateway", {}).get("url", "").rstrip("/")
        gw_token = cfg.get("gateway", {}).get("token", "")

        if not gw_url:
            self._json_error(503, "Gateway URL not configured in config.json")
            return

        length   = int(self.headers.get("Content-Length", 0))
        body     = self.rfile.read(length)
        endpoint = f"{gw_url}/tools/invoke"

        req = Request(
            endpoint,
            data=body,
            headers={
                "Content-Type":  "application/json",
                "Authorization": f"Bearer {gw_token}"
            },
            method="POST"
        )
        try:
            with urlopen(req, timeout=30) as resp:
                resp_body = resp.read()
                self.send_response(resp.status)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(resp_body)))
                self.send_cors()
                self.end_headers()
                self.wfile.write(resp_body)
        except URLError as e:
            self._json_error(502, f"Gateway unreachable: {e.reason}")
        except Exception as e:
            self._json_error(500, str(e))

    # ── /proxy/config — write config.json directly (no gateway needed) ────────
    def _write_config(self):
        length = int(self.headers.get("Content-Length", 0))
        body   = self.rfile.read(length)
        try:
            new_cfg = json.loads(body)
            # Merge thresholds only (safe partial update)
            existing = load_config()
            if "thresholds" in new_cfg:
                existing.setdefault("thresholds", {}).update(new_cfg["thresholds"])
            with open(CONFIG_PATH, "w") as f:
                json.dump(existing, f, indent=2)
            resp = json.dumps({"ok": True}).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(resp)))
            self.send_cors()
            self.end_headers()
            self.wfile.write(resp)
            print(f"[serve] config.json updated — thresholds: {new_cfg.get('thresholds','')}")
        except Exception as e:
            self._json_error(500, str(e))

    # ── /proxy/data/<filename> — serve data/*.json files ─────────────────────
    def _serve_data_file(self):
        # Extract filename from path: /proxy/data/queue.json -> queue.json
        filename = self.path.replace("/proxy/data/", "", 1)

        # Security: only allow .json files, no path traversal
        if not filename.endswith(".json") or "/" in filename or "\\" in filename or ".." in filename:
            self._json_error(400, "Invalid filename — must be a .json file without path separators")
            return

        filepath = os.path.join(SCRIPT_DIR, "data", filename)
        if not os.path.exists(filepath):
            self._json_error(404, f"File not found: data/{filename}")
            return

        try:
            with open(filepath, "r") as f:
                content = f.read()
            body = content.encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.send_cors()
            self.end_headers()
            self.wfile.write(body)
        except Exception as e:
            self._json_error(500, str(e))

    # ── /proxy/agent-prompt/<name> — serve agent PROMPT.md with path filled ──
    def _serve_agent_prompt(self):
        # Extract agent name from path: /proxy/agent-prompt/trends -> trends
        name = self.path.replace("/proxy/agent-prompt/", "", 1).strip("/")

        # Security: only allow known agent names
        allowed_agents = {"trends", "scout", "lister", "midas", "feed"}
        if name not in allowed_agents:
            self._json_error(404, f"Agent not found: {name}. Allowed: {', '.join(sorted(allowed_agents))}")
            return

        prompt_path = os.path.join(SCRIPT_DIR, "agents", name, "PROMPT.md")
        if not os.path.exists(prompt_path):
            self._json_error(404, f"PROMPT.md not found for agent: {name}")
            return

        try:
            with open(prompt_path, "r") as f:
                content = f.read()

            # Replace {{REPO_PATH}} with actual repo path
            content = content.replace("{{REPO_PATH}}", SCRIPT_DIR)

            resp = json.dumps({"name": name, "prompt": content})
            body = resp.encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.send_cors()
            self.end_headers()
            self.wfile.write(body)
        except Exception as e:
            self._json_error(500, str(e))

    # ── Google OAuth state (in-memory, per server process) ───────────────
    _google_oauth_state: dict = {}   # class-level shared state

    # ── /setup/google-auth/start ──────────────────────────────────────────
    def _google_auth_start(self):
        length = int(self.headers.get("Content-Length", 0))
        body   = json.loads(self.rfile.read(length))
        cid      = body.get("clientId", "").strip() or GC_GOOGLE_CLIENT_ID
        csecret  = body.get("clientSecret", "").strip() or GC_GOOGLE_CLIENT_SECRET
        dev_tok  = body.get("developerToken", "").strip()
        port     = self.server.server_address[1]
        public_base = os.environ.get("GC_PUBLIC_BASE_URL", "").rstrip("/")
        redirect = f"{public_base}/setup/google-auth/callback" if public_base else f"http://localhost:{port}/setup/google-auth/callback"

        import urllib.parse, secrets
        state = secrets.token_hex(8)
        GCHandler._google_oauth_state = {
            "state": state, "clientId": cid,
            "clientSecret": csecret, "developerToken": dev_tok,
            "redirect": redirect, "status": "pending"
        }
        params = urllib.parse.urlencode({
            "client_id": cid,
            "redirect_uri": redirect,
            "response_type": "code",
            "scope": "https://www.googleapis.com/auth/adwords",
            "access_type": "offline",
            "prompt": "consent",
            "state": state,
        })
        auth_url = f"https://accounts.google.com/o/oauth2/v2/auth?{params}"
        resp = json.dumps({"ok": True, "authUrl": auth_url}).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(resp)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(resp)

    # ── /setup/google-auth/callback ───────────────────────────────────────
    def _google_auth_callback(self):
        from urllib.parse import urlparse, parse_qs
        from urllib.request import Request as UReq, urlopen as uopen
        qs    = parse_qs(urlparse(self.path).query)
        code  = qs.get("code", [""])[0]
        state = qs.get("state", [""])[0]
        st    = GCHandler._google_oauth_state

        if not code or state != st.get("state", ""):
            html = b"<h2>Error: invalid state or missing code. Close this tab and try again.</h2>"
            self.send_response(400)
            self.send_header("Content-Type", "text/html")
            self.send_header("Content-Length", str(len(html)))
            self.end_headers()
            self.wfile.write(html)
            return

        try:
            # Exchange code for tokens
            payload = json.dumps({
                "code": code, "client_id": st["clientId"],
                "client_secret": st["clientSecret"],
                "redirect_uri": st["redirect"],
                "grant_type": "authorization_code",
            }).encode()
            req = UReq("https://oauth2.googleapis.com/token",
                       data=payload, headers={"Content-Type": "application/json"}, method="POST")
            with uopen(req, timeout=10) as r:
                tokens = json.loads(r.read())

            refresh_token = tokens.get("refresh_token", "")
            access_token  = tokens.get("access_token", "")

            # Get accessible customer IDs
            req2 = UReq(
                "https://googleads.googleapis.com/v18/customers:listAccessibleCustomers",
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "developer-token": st["developerToken"],
                }
            )
            customer_ids = []
            customers_error = ""
            try:
                with uopen(req2, timeout=15) as r:
                    data = json.loads(r.read())
                    # resourceNames like "customers/1234567890"
                    customer_ids = [
                        rn.split("/")[-1]
                        for rn in data.get("resourceNames", [])
                    ]
            except Exception as ce:
                customers_error = str(ce)
                import traceback, sys
                print(f"[GoogleClaw] listAccessibleCustomers error: {ce}", flush=True)

            GCHandler._google_oauth_state.update({
                "status": "done",
                "refreshToken": refresh_token,
                "customerIds": customer_ids,
                "customersError": customers_error,
                "hasRefreshToken": bool(refresh_token),
                "tokenKeys": list(tokens.keys()),
            })

            # Close tab and notify opener
            html = b"""<!DOCTYPE html>
<html><head><title>GoogleClaw - Google Connected</title>
<style>body{font-family:sans-serif;background:#040B1B;color:#D3D8F2;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}</style>
</head><body>
<div style="text-align:center">
  <div style="font-size:48px;margin-bottom:16px">&#10003;</div>
  <h2>Google Ads connected!</h2>
  <p>You can close this tab and return to the setup wizard.</p>
</div>
<script>
  if(window.opener){ window.opener.postMessage({type:'google-auth-done'},'*'); }
  setTimeout(()=>window.close(),2000);
</script>
</body></html>"""
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.send_header("Content-Length", str(len(html)))
            self.end_headers()
            self.wfile.write(html)

        except Exception as e:
            GCHandler._google_oauth_state["status"] = f"error: {e}"
            html = f"<h2>Auth error: {e}</h2>".encode()
            self.send_response(500)
            self.send_header("Content-Type", "text/html")
            self.send_header("Content-Length", str(len(html)))
            self.end_headers()
            self.wfile.write(html)

    # ── /setup/google-auth/status ─────────────────────────────────────────
    def _google_auth_status(self):
        st   = GCHandler._google_oauth_state
        resp = json.dumps({
            "status":        st.get("status", "pending"),
            "customerIds":   st.get("customerIds", []),
            "refreshToken":  st.get("refreshToken", ""),
            "hasRefreshToken": st.get("hasRefreshToken", False),
            "customersError": st.get("customersError", ""),
            "tokenKeys":     st.get("tokenKeys", []),
        }).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(resp)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(resp)

    # ── /setup/test-shopify ───────────────────────────────────────────────
    def _setup_test_shopify(self):
        length = int(self.headers.get("Content-Length", 0))
        body   = json.loads(self.rfile.read(length))
        domain      = body.get("storeDomain", "").strip().rstrip("/")
        cid         = body.get("clientId", "").strip()
        csecret     = body.get("clientSecret", "").strip()
        static_tok  = body.get("staticToken", "").strip()
        try:
            from urllib.request import Request as UReq, urlopen as uopen
            # Static token path (legacy custom app)
            if static_tok:
                token = static_tok
            else:
                # Client credentials grant (new app via Partners portal)
                payload = json.dumps({
                    "client_id": cid, "client_secret": csecret,
                    "grant_type": "client_credentials"
                }).encode()
                req = UReq(f"https://{domain}/admin/oauth/access_token",
                           data=payload, headers={"Content-Type": "application/json"}, method="POST")
                try:
                    with uopen(req, timeout=10) as r:
                        raw = r.read()
                        result = json.loads(raw)
                        token = result.get("access_token", "")
                except Exception as http_err:
                    # Capture Shopify's actual error body
                    import urllib.error
                    if hasattr(http_err, 'read'):
                        body = http_err.read().decode('utf-8', errors='replace')
                        raise ValueError(f"Shopify error: {body}")
                    raise ValueError(f"HTTP error: {http_err}")
                if not token:
                    raise ValueError(f"No token in response: {result}")
            req2 = UReq(f"https://{domain}/admin/api/2024-01/shop.json",
                        headers={"X-Shopify-Access-Token": token})
            with uopen(req2, timeout=8) as r:
                name = json.loads(r.read()).get("shop", {}).get("name", "unknown")
            resp = json.dumps({"ok": True, "storeName": name}).encode()
            self.send_response(200)
        except Exception as e:
            resp = json.dumps({"ok": False, "error": str(e)}).encode()
            self.send_response(400)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(resp)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(resp)

    # ── /setup/save — write config.json + register crons ─────────────────
    def _setup_save(self):
        length = int(self.headers.get("Content-Length", 0))
        data   = json.loads(self.rfile.read(length))
        try:
            # Accept snake_case (frontend form names) OR camelCase (legacy)
            def g(snake, camel=None, default=""):
                v = data.get(snake) or (data.get(camel) if camel else None)
                return v if v is not None else default

            def flt(snake, camel, default):
                try: return float(g(snake, camel, default) or default)
                except: return float(default)

            def intt(snake, camel, default):
                try: return int(g(snake, camel, default) or default)
                except: return int(default)

            cfg = {
                "instance": {
                    "name":     g("store_name", "storeName"),
                    "owner":    g("your_name", "ownerName"),
                    "bot_name": g("agent_name", "botName"),
                    "timezone": g("timezone", default="Europe/Amsterdam"),
                },
                "store": {
                    "niche":    g("niche"),
                    "market":   g("market"),
                    "language": g("store_language", "language", "Dutch"),
                },
                "shopify": {
                    "storeDomain":  g("shopify_domain", "storeDomain"),
                    "accessToken":  g("shopify_static_token", "shopifyStaticToken"),
                    "clientId":     g("shopify_client_id", "shopifyClientId"),
                    "clientSecret": g("shopify_client_secret", "shopifyClientSecret"),
                },
                "googleAds": {
                    "customerId":    g("google_ads_customer_id", "gadsCustomerId"),
                    "developerToken": g("google_ads_developer_token", "gadsDeveloperToken"),
                    "clientId":      g("google_ads_oauth_client_id", "gadsClientId"),
                    "clientSecret":  g("google_ads_oauth_client_secret", "gadsClientSecret"),
                    "refreshToken":  g("google_ads_refresh_token", "gadsRefreshToken"),
                },
                "cj": {
                    "email":    g("cj_email", "cjEmail"),
                    "password": g("cj_password", "cjPassword"),
                },
                "apify":    {"token": g("apify_token", "apifyToken")},
                "openai":   {"apiKey": g("openai_key", "openaiKey")},
                "anthropic":{"apiKey": g("anthropic_key", "anthropicKey")},
                "gemini":   {"apiKey": g("gemini_key", "geminiKey")},
                "manus":    {"apiKey": g("manus_api_key", "manusKey")},
                "openclaw": {
                    "gatewayUrl":   g("openclaw_gateway_url", "gatewayUrl"),
                    "gatewayToken": g("openclaw_gateway_token", "gatewayToken"),
                },
                "notifications": {
                    "telegram": {
                        "enabled":  bool(g("telegram_bot_token", "telegramToken")),
                        "botToken": g("telegram_bot_token", "telegramToken"),
                        "chatId":   g("telegram_chat_id", "telegramChatId"),
                    }
                },
                "competitorSheet": g("competitor_sheet", "competitorSheet"),
                "thresholds": {
                    "scale_roas":    flt("scale_trigger_roas",   "scaleRoas",     3.0),
                    "alert_roas":    flt("alert_trigger_roas",   "alertRoas",     1.0),
                    "alert_days":    intt("alert_after_days",    "alertDays",     3),
                    "min_price":     flt("min_selling_price",    "minPrice",      40),
                    "autopub_score": intt("auto_publish_score",  "autopubScore",  75),
                    "daily_limit":   intt("daily_candidate_limit","dailyLimit",   10),
                },
                "costs": {
                    "shopifyMonthly": 39,
                    "shopifyPaymentsFeePercent": 1.9,
                    "shopifyPaymentsFeeFixed": 0.25,
                    "defaultMarginPercent": 40,
                },
            }
            # Write config.json
            os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
            with open(CONFIG_PATH, "w") as f:
                json.dump(cfg, f, indent=2)
            os.chmod(CONFIG_PATH, 0o600)

            # Register crons
            cron_results = []
            tz       = cfg["instance"]["timezone"]
            repo     = SCRIPT_DIR
            crons = [
                ("gc-trends", "0 23 * * 0", "trends",  "openai/gpt-5.1-codex", 600,  "TRENDS — zondag 23:00"),
                ("gc-scout",  "0 6 * * *",  "scout",   "openai/gpt-5.1-codex", 900,  "SCOUT — dagelijks 06:00"),
                ("gc-midas",  "0 7 * * *",  "midas",   "openai/gpt-5.1-codex", 600,  "MIDAS — dagelijks 07:00"),
                ("gc-feed",   "0 6 * * 3",  "feed",    "openai/gpt-5.1-codex", 600,  "FEED — woensdags 06:00"),
            ]
            import subprocess as sp
            for name, schedule, agent_id, model, timeout, desc in crons:
                prompt_path = os.path.join(repo, "agents", agent_id, "PROMPT.md")
                if os.path.exists(prompt_path):
                    with open(prompt_path) as pf:
                        prompt = pf.read().replace("{{REPO_PATH}}", repo)
                    result = sp.run(
                        ["openclaw", "cron", "add",
                         "--name", name, "--cron", schedule, "--tz", tz,
                         "--message", prompt, "--session", "isolated",
                         "--model", model, "--timeout-seconds", str(timeout),
                         "--description", desc],
                        capture_output=True, text=True, timeout=15
                    )
                    cron_results.append({
                        "name": name,
                        "ok": result.returncode == 0,
                        "msg": result.stderr.strip() or "registered"
                    })

            resp = json.dumps({"ok": True, "success": True, "crons": cron_results}).encode()
            self.send_response(200)
        except Exception as e:
            resp = json.dumps({"ok": False, "error": str(e)}).encode()
            self.send_response(500)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(resp)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(resp)

    def _json_error(self, code, msg):
        body = json.dumps({"error": msg}).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        # Only log proxy calls and errors, not every static file
        path = args[0] if args else ""
        if "proxy" in str(path) or str(args[1] if len(args)>1 else "").startswith(("4","5")):
            super().log_message(fmt, *args)


# ── Main ──────────────────────────────────────────────────────────────────────
def check_security():
    """Warn about insecure config.json permissions."""
    if not os.path.exists(CONFIG_PATH):
        return
    mode = oct(os.stat(CONFIG_PATH).st_mode)[-3:]
    if mode not in ("600", "400"):
        print(f"[serve] ⚠  WARNING: config.json has permissions {mode} — should be 600")
        print(f"[serve]    Fix: chmod 600 {CONFIG_PATH}")
    else:
        print(f"[serve] ✓  config.json permissions: {mode}")

def main():
    parser = argparse.ArgumentParser(description="GoogleClaw local server")
    parser.add_argument("--port",       type=int, default=8080)
    parser.add_argument("--no-browser", action="store_true")
    args = parser.parse_args()

    cfg = load_config()
    inst = cfg.get("instance", {})
    store_name = inst.get("name", "GoogleClaw")

    if not os.path.isdir(FRONTEND_DIR):
        print(f"[serve] ✗  frontend/ directory not found at {FRONTEND_DIR}")
        sys.exit(1)

    check_security()

    bind   = os.environ.get("GC_HOST", "127.0.0.1")
    server = HTTPServer((bind, args.port), GCHandler)
    url    = f"http://{bind}:{args.port}/web.html"

    print()
    print(f"  ┌─────────────────────────────────────────┐")
    print(f"  │  GoogleClaw — {store_name:<26}│")
    print(f"  │  Local server running                   │")
    print(f"  │                                         │")
    print(f"  │  {url:<41}│")
    print(f"  │                                         │")
    print(f"  │  Press Ctrl+C to stop                   │")
    print(f"  └─────────────────────────────────────────┘")
    print()

    if not args.no_browser:
        threading.Timer(0.8, lambda: webbrowser.open(url)).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[serve] Stopped.")

if __name__ == "__main__":
    main()
