#!/usr/bin/env python3
"""
GoogleClaw — Local Server
Serves the frontend, proxies gateway calls, and auto-connects from config.json.

Usage:
  python3 serve.py                  # default port 8080
  python3 serve.py --port 9090
  python3 serve.py --no-browser     # don't auto-open browser
"""

import json
import os
import sys
import threading
import webbrowser
import argparse
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.request import urlopen, Request
from urllib.error import URLError
import urllib.parse

# ── Config ────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH  = os.path.join(SCRIPT_DIR, "config.json")
FRONTEND_DIR = os.path.join(SCRIPT_DIR, "frontend")

def load_config():
    if not os.path.exists(CONFIG_PATH):
        print(f"[serve] ⚠  config.json not found at {CONFIG_PATH}")
        print("[serve]    Run `python3 setup.py` first to create it.")
        return {}
    with open(CONFIG_PATH) as f:
        return json.load(f)

# ── Handler ───────────────────────────────────────────────────────────────────
class GCHandler(SimpleHTTPRequestHandler):
    """Serves frontend/ static files + /bootstrap.js + /proxy/tools/invoke"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=FRONTEND_DIR, **kwargs)

    # ── CORS headers ──────────────────────────────────────────────────────────
    def send_cors(self):
        self.send_header("Access-Control-Allow-Origin",  "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_cors()
        self.end_headers()

    # ── Dynamic routes ────────────────────────────────────────────────────────
    def do_GET(self):
        if self.path == "/bootstrap.js":
            self._serve_bootstrap()
        elif self.path in ("/", ""):
            self.path = "/web.html"
            super().do_GET()
        else:
            super().do_GET()

    def do_POST(self):
        if self.path == "/proxy/tools/invoke":
            self._proxy_invoke()
        elif self.path == "/proxy/config":
            self._write_config()
        else:
            self.send_response(404)
            self.end_headers()

    # ── /bootstrap.js — auto-connect config for the frontend ─────────────────
    def _serve_bootstrap(self):
        cfg = load_config()
        gw_url   = cfg.get("gateway", {}).get("url", "")
        gw_token = cfg.get("gateway", {}).get("token", "")
        inst     = cfg.get("instance", {})
        store    = cfg.get("store", {})
        thresh   = cfg.get("thresholds", {})

        js = f"""// Auto-generated by serve.py — do not edit manually
window.GC_BOOTSTRAP = {{
  gatewayUrl:   "/proxy/tools/invoke",
  gatewayToken: "{gw_token}",
  managed:      true,
  instance: {{
    name:     "{inst.get('name','')}",
    owner:    "{inst.get('owner','')}",
    botName:  "{inst.get('bot_name','')}",
    timezone: "{inst.get('timezone','Europe/Amsterdam')}"
  }},
  store: {{
    niche:    "{store.get('niche','')}",
    market:   "{store.get('market','')}",
    language: "{store.get('language','')}"
  }},
  thresholds: {{
    scale_roas:    {thresh.get('scale_roas', 3.0)},
    alert_roas:    {thresh.get('alert_roas', 1.0)},
    alert_days:    {thresh.get('alert_days', 3)},
    min_price:     {thresh.get('min_price', 40)},
    autopub_score: {thresh.get('autopub_score', 75)},
    daily_limit:   {thresh.get('daily_limit', 10)}
  }}
}};
"""
        body = js.encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/javascript")
        self.send_header("Content-Length", str(len(body)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(body)

    # ── /proxy/tools/invoke — proxy to OpenClaw gateway ──────────────────────
    def _proxy_invoke(self):
        cfg      = load_config()
        gw_url   = cfg.get("gateway", {}).get("url", "").rstrip("/")
        gw_token = cfg.get("gateway", {}).get("token", "")

        if not gw_url:
            self._json_error(503, "Gateway URL not configured in config.json")
            return

        length   = int(self.headers.get("Content-Length", 0))
        body     = self.rfile.read(length)
        endpoint = f"{gw_url}/tools/invoke"

        req = Request(
            endpoint,
            data=body,
            headers={
                "Content-Type":  "application/json",
                "Authorization": f"Bearer {gw_token}"
            },
            method="POST"
        )
        try:
            with urlopen(req, timeout=30) as resp:
                resp_body = resp.read()
                self.send_response(resp.status)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(resp_body)))
                self.send_cors()
                self.end_headers()
                self.wfile.write(resp_body)
        except URLError as e:
            self._json_error(502, f"Gateway unreachable: {e.reason}")
        except Exception as e:
            self._json_error(500, str(e))

    # ── /proxy/config — write config.json directly (no gateway needed) ────────
    def _write_config(self):
        length = int(self.headers.get("Content-Length", 0))
        body   = self.rfile.read(length)
        try:
            new_cfg = json.loads(body)
            # Merge thresholds only (safe partial update)
            existing = load_config()
            if "thresholds" in new_cfg:
                existing.setdefault("thresholds", {}).update(new_cfg["thresholds"])
            with open(CONFIG_PATH, "w") as f:
                json.dump(existing, f, indent=2)
            resp = json.dumps({"ok": True}).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(resp)))
            self.send_cors()
            self.end_headers()
            self.wfile.write(resp)
            print(f"[serve] config.json updated — thresholds: {new_cfg.get('thresholds','')}")
        except Exception as e:
            self._json_error(500, str(e))

    def _json_error(self, code, msg):
        body = json.dumps({"error": msg}).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_cors()
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        # Only log proxy calls and errors, not every static file
        path = args[0] if args else ""
        if "proxy" in str(path) or str(args[1] if len(args)>1 else "").startswith(("4","5")):
            super().log_message(fmt, *args)


# ── Main ──────────────────────────────────────────────────────────────────────
def check_security():
    """Warn about insecure config.json permissions."""
    if not os.path.exists(CONFIG_PATH):
        return
    mode = oct(os.stat(CONFIG_PATH).st_mode)[-3:]
    if mode not in ("600", "400"):
        print(f"[serve] ⚠  WARNING: config.json has permissions {mode} — should be 600")
        print(f"[serve]    Fix: chmod 600 {CONFIG_PATH}")
    else:
        print(f"[serve] ✓  config.json permissions: {mode}")

def main():
    parser = argparse.ArgumentParser(description="GoogleClaw local server")
    parser.add_argument("--port",       type=int, default=8080)
    parser.add_argument("--no-browser", action="store_true")
    args = parser.parse_args()

    cfg = load_config()
    inst = cfg.get("instance", {})
    store_name = inst.get("name", "GoogleClaw")

    if not os.path.isdir(FRONTEND_DIR):
        print(f"[serve] ✗  frontend/ directory not found at {FRONTEND_DIR}")
        sys.exit(1)

    check_security()

    server = HTTPServer(("127.0.0.1", args.port), GCHandler)
    url    = f"http://127.0.0.1:{args.port}/web.html"

    print()
    print(f"  ┌─────────────────────────────────────────┐")
    print(f"  │  GoogleClaw — {store_name:<26}│")
    print(f"  │  Local server running                   │")
    print(f"  │                                         │")
    print(f"  │  {url:<41}│")
    print(f"  │                                         │")
    print(f"  │  Press Ctrl+C to stop                   │")
    print(f"  └─────────────────────────────────────────┘")
    print()

    if not args.no_browser:
        threading.Timer(0.8, lambda: webbrowser.open(url)).start()

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[serve] Stopped.")

if __name__ == "__main__":
    main()
